---
- name: Create OpenShift Agent Based Installation manifests
  hosts: localhost
  gather_facts: false

  tasks:

    - name: Make a directory for the per-cluster manifests
      ansible.builtin.file:
        path: "./generated_manifests/{{ cluster_name }}"
        state: directory
        mode: '0755'

    - name: Generate the SSH key pair
      when: ssh_public_key_path is not defined
      block:
        - name: Check to see if the key pair already exists
          ansible.builtin.stat:
            path: "./generated_manifests/{{ cluster_name }}/ssh_key"
          register: ssh_key_exists

        - name: Create a new key pair for the cluster
          when: not ssh_key_exists.stat.exists
          community.crypto.openssh_keypair:
            path: "./generated_manifests/{{ cluster_name }}/ssh_key"
            type: rsa
            state: present
            size: 4096
            mode: '0600'

        - name: Set the fact for the ssh_public_key_path
          ansible.builtin.set_fact:
            ssh_public_key_path: "./generated_manifests/{{ cluster_name }}/ssh_key.pub"

    - name: Template the install-config.yml file
      ansible.builtin.template:
        src: install-config.yml.j2
        dest: "./generated_manifests/{{ cluster_name }}/install-config.yaml"
        mode: '0644'

    - name: Template the agent-config.yml file
      ansible.builtin.template:
        src: agent-config.yml.j2
        dest: "./generated_manifests/{{ cluster_name }}/agent-config.yaml"
        mode: '0644'

    - name: Template the ZTP manifests
      when: create_ztp_manifests
      ansible.builtin.template:
        src: "{{ manifest_item }}.yml.j2"
        dest: "./generated_manifests/{{ cluster_name }}/{{ manifest_item }}.yaml"
        mode: '0644'
      loop:
        - agentclusterinstall
        - clusterdeployment
        - clusterimageset
        - pull-secret
      loop_control:
        loop_var: manifest_item

    - name: Template the ImageDigestMirrorSet and the ImageTagMirrorSet if this is a disconnected install
      when: disconnected_registries is defined
      ansible.builtin.template:
        src: imagedigestmirrorset.yml.j2
        dest: "./generated_manifests/{{ cluster_name }}/image-mirror-config.yaml"
        mode: '0644'